#!/bin/bash
set -e

gsutil cp gs://socket-resources/gohere.zip .

unzip -o gohere.zip

if [[ $UID != 0 ]]; then
        echo "Please run this script with sudo:"
        echo "sudo $0 $*"
        exit 1
fi

if [ -f gohere.pid ]
then
        kill $(cat gohere.pid)
fi

./gohere &>> gohere.log &

pid=$!

echo $pid > gohere.pid

disown $pid

echo "Done, disowned process of pid $pid!"